# Generated by Django 5.2.15 on 2026-06-05 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('patient', 'Пациент'), ('doctor', 'Врач'), ('admin', 'Администратор')], max_length=10)),
                ('iin', models.CharField(max_length=12, unique=True, verbose_name='ИИН')),
                ('password', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=150, verbose_name='ФИО')),
                ('age', models.CharField(blank=True, max_length=20, null=True)),
                ('gender', models.CharField(blank=True, max_length=20, null=True)),
                ('birth_date', models.CharField(blank=True, max_length=20, null=True)),
                ('blood_type', models.CharField(blank=True, max_length=20, null=True)),
                ('phone', models.CharField(blank=True, max_length=30, null=True)),
                ('clinic', models.CharField(blank=True, max_length=150, null=True)),
                ('district', models.CharField(blank=True, max_length=50, null=True)),
                ('symptoms', models.TextField(blank=True, null=True)),
                ('chronic', models.TextField(blank=True, null=True)),
                ('specialization', models.CharField(blank=True, max_length=150, null=True)),
                ('experience', models.CharField(blank=True, max_length=20, null=True)),
                ('workplace', models.CharField(blank=True, max_length=150, null=True)),
                ('schedule', models.CharField(blank=True, max_length=100, null=True)),
                ('institution', models.CharField(blank=True, max_length=150, null=True)),
                ('address', models.CharField(blank=True, max_length=250, null=True)),
            ],
        ),
    ]
